apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-quota
  namespace: hello-world
spec:
  hard:
    pods: "4"                        # Max number of pods
    requests.cpu: "4"                 # Total CPU requests
    requests.memory: 8Gi              # Total memory requests
    limits.cpu: "8"                   # Total CPU limits
    limits.memory: 16Gi              # Total memory limits
    persistentvolumeclaims: "5"       # Max PVCs
    services.loadbalancers: "2"       # Max LoadBalancer services
